const departments = [
  {id:'administrasi',name:'Administrasi',icon:'✎',desc:'Menjaga tata kelola, arsip, dan administrasi organisasi.',lead:'Aulia Rahmah',role:'Kepala Departemen'},
  {id:'hubungan-luar',name:'Hubungan Luar',icon:'⌁',desc:'Membangun relasi, kemitraan, dan jejaring eksternal.',lead:'Muh. Fikri',role:'Kepala Departemen'},
  {id:'dana-usaha',name:'Dana dan Usaha',icon:'↗',desc:'Mengembangkan kemandirian ekonomi dan peluang usaha.',lead:'Nabila Azzahra',role:'Kepala Departemen'},
  {id:'jaringan-komunikasi',name:'Jaringan & Komunikasi',icon:'◌',desc:'Menghubungkan informasi dan komunikasi organisasi.',lead:'Ahmad Rasyid',role:'Kepala Departemen'},
  {id:'minat-bakat',name:'Pengembangan Minat & Bakat',icon:'✺',desc:'Merayakan potensi, kreativitas, dan prestasi mahasiswa.',lead:'Siti Nurhaliza',role:'Kepala Departemen'},
  {id:'pengabdian-masyarakat',name:'Pengabdian Masyarakat',icon:'♡',desc:'Menghubungkan kampus dengan kebutuhan masyarakat.',lead:'Farhan Akbar',role:'Kepala Departemen'},
  {id:'kajian-advokasi',name:'Kajian Strategi & Advokasi',icon:'⚖',desc:'Mengawal isu strategis dan kesejahteraan mahasiswa.',lead:'Nurfadillah',role:'Kepala Departemen'},
  {id:'pendidikan-penelitian',name:'Pendidikan & Penelitian',icon:'◈',desc:'Menyalakan budaya belajar dan penelitian ilmiah.',lead:'Rizky Ananda',role:'Kepala Departemen'},
  {id:'pengembangan-sdm',name:'Pengembangan SDM',icon:'✦',desc:'Menyiapkan sumber daya manusia yang tangguh dan adaptif.',lead:'M. Ilham',role:'Kepala Departemen'},
  {id:'ilmu-karakter-islam',name:'Pengembangan Ilmu & Karakter Islam',icon:'☾',desc:'Menumbuhkan ilmu dan karakter berlandaskan nilai Islam.',lead:'Aisyah Humaira',role:'Kepala Departemen'}
];
const core = [['Raihan Fadillah','Ketua Umum'],['Nur Aini','Wakil Ketua'],['Aulia Rahmah','Sekretaris Umum'],['Muh. Fikri','Bendahara Umum']];
const app=document.querySelector('#app'), nav=document.querySelector('#navigation');
const initials=n=>n.split(' ').map(x=>x[0]).slice(0,2).join('');
function renderNav(active){nav.innerHTML=`<a class="${active==='beranda'?'active':''}" href="#beranda">Main Room <span>00</span></a>`+departments.map((d,i)=>`<a class="${active===d.id?'active':''}" href="#${d.id}">${d.name}<span>${String(i+1).padStart(2,'0')}</span></a>`).join('');}
function home(){app.innerHTML=document.querySelector('#home-template').innerHTML;renderNav('beranda');document.querySelector('#leaders').innerHTML=core.map(([name,role])=>`<article class="leader"><div class="avatar">${initials(name)}</div><div><p>${role}</p><h3>${name}</h3></div></article>`).join('');document.querySelector('#department-list').innerHTML=departments.map((d,i)=>`<a class="department-row" href="#${d.id}"><div class="dept-symbol">${d.icon}</div><h3>${d.name}</h3><p>${d.desc}</p><span class="arrow">↗</span></a>`).join(''); const agendas=[['Kelas Klinik','Pendidikan & Penelitian',3],['Medical Charity','Pengabdian Masyarakat',11],['Pekan Olahraga Medika','Pengembangan Minat & Bakat',18]];document.querySelector('#agenda-list').innerHTML=agendas.map(([title,dept,plus])=>{let d=new Date();d.setDate(d.getDate()+plus);return `<article class="agenda-item"><time>${d.toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase()}</time><div><h3>${title}</h3><p>${dept}</p></div><span>PROGRAM KERJA</span></article>`}).join('');}
function room(id){const d=departments.find(x=>x.id===id);if(!d)return home();app.innerHTML=document.querySelector('#department-template').innerHTML;renderNav(id);const index=departments.indexOf(d)+1;document.querySelector('#room-number').textContent=String(index).padStart(2,'0');document.querySelector('#room-icon').textContent=d.icon;document.querySelector('#room-eyebrow').textContent=`RUANG ${String(index).padStart(2,'0')} — DEPARTEMEN`;document.querySelector('#room-title').textContent=d.name;document.querySelector('#room-description').textContent=d.desc;const people=[[d.lead,d.role],['Nadia Putri','Sekretaris Departemen'],['Ardiansyah','Staf Program'],['Miftahul Jannah','Staf Program'],['Dimas Pratama','Staf Media'],['Salsabila','Staf Media']];document.querySelector('#team-list').innerHTML=people.map(([name,role])=>`<article class="team-member"><div class="mini-avatar">${initials(name)}</div><div><h3>${name}</h3><p>${role}</p></div></article>`).join('');const docs=['Rapat Kerja Departemen','Program Unggulan','Aksi Kolaborasi'];document.querySelector('#documentation').innerHTML=docs.map((x,i)=>`<article class="doc-card"><span>0${i+1} / ${new Date().getFullYear()}</span><h3>${x}</h3><p>${d.name}</p></article>`).join('');}
function route(){let id=location.hash.slice(1)||'beranda';const homeSections=['beranda','tentang','pengurus','departemen','program'];if(homeSections.includes(id)){home();requestAnimationFrame(()=>document.querySelector(id==='beranda'?'.hero':`#${id}`)?.scrollIntoView({block:'start'}));}else room(id);document.querySelector('#sidebar').classList.remove('open');}
window.addEventListener('hashchange',route);route();
const date=new Date();document.querySelector('#live-date').textContent=date.toLocaleDateString('id-ID',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).toUpperCase();document.querySelector('#year').textContent=date.getFullYear();
document.querySelector('.menu-toggle').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');
const panel=document.querySelector('#color-panel');document.querySelector('#customizer-toggle').onclick=()=>{panel.classList.toggle('open');document.querySelector('#customizer-toggle').setAttribute('aria-expanded',panel.classList.contains('open'));};
const defaults={forest:'#14532D',grass:'#4CAF50',yellow:'#FFC107'};document.querySelectorAll('[data-color]').forEach(input=>{let c=localStorage.getItem('color-'+input.dataset.color)||input.value;input.value=c;document.documentElement.style.setProperty('--'+input.dataset.color,c);input.oninput=()=>{document.documentElement.style.setProperty('--'+input.dataset.color,input.value);localStorage.setItem('color-'+input.dataset.color,input.value)}});document.querySelector('#reset-colors').onclick=()=>{Object.entries(defaults).forEach(([key,value])=>{localStorage.removeItem('color-'+key);document.documentElement.style.setProperty('--'+key,value);document.querySelector(`[data-color="${key}"]`).value=value})};
