const departments = [
  {id:'sekretaris',name:'Sekretaris',icon:'✎',desc:'Menjaga ritme administrasi dan informasi organisasi.',lead:'Aulia Rahmah',role:'Kepala Sekretaris'},
  {id:'bendahara',name:'Bendahara',icon:'₊',desc:'Mengelola sumber daya dengan transparan dan bertanggung jawab.',lead:'Muh. Fikri',role:'Kepala Bendahara'},
  {id:'kaderisasi',name:'Kaderisasi',icon:'⌁',desc:'Menyiapkan kader yang tangguh, adaptif, dan berintegritas.',lead:'Nabila Azzahra',role:'Kepala Departemen'},
  {id:'akademik',name:'Akademik & Keilmuan',icon:'◈',desc:'Menyalakan budaya belajar dan diskusi ilmiah.',lead:'Ahmad Rasyid',role:'Kepala Departemen'},
  {id:'minat-bakat',name:'Minat & Bakat',icon:'✺',desc:'Merayakan potensi, kreativitas, dan prestasi mahasiswa.',lead:'Siti Nurhaliza',role:'Kepala Departemen'},
  {id:'sosial',name:'Sosial Masyarakat',icon:'♡',desc:'Menghubungkan kampus dengan denyut kebutuhan masyarakat.',lead:'Farhan Akbar',role:'Kepala Departemen'},
  {id:'kominfo',name:'Komunikasi & Informasi',icon:'◌',desc:'Merangkai cerita organisasi melalui komunikasi yang bermakna.',lead:'Nurfadillah',role:'Kepala Departemen'},
  {id:'dana-usaha',name:'Dana & Usaha',icon:'↗',desc:'Mengembangkan kemandirian ekonomi dan jejaring kemitraan.',lead:'Rizky Ananda',role:'Kepala Departemen'},
  {id:'advokasi',name:'Advokasi & Kesejahteraan',icon:'⚖',desc:'Mengawal suara dan kesejahteraan mahasiswa kedokteran.',lead:'M. Ilham',role:'Kepala Departemen'},
  {id:'keagamaan',name:'Keagamaan',icon:'☾',desc:'Menumbuhkan spiritualitas dalam setiap langkah pengabdian.',lead:'Aisyah Humaira',role:'Kepala Departemen'}
];
const core = [['Raihan Fadillah','Ketua Umum'],['Nur Aini','Wakil Ketua'],['Aulia Rahmah','Sekretaris Umum'],['Muh. Fikri','Bendahara Umum']];
const app=document.querySelector('#app'), nav=document.querySelector('#navigation');
const initials=n=>n.split(' ').map(x=>x[0]).slice(0,2).join('');
function saveEditable(){document.querySelectorAll('[contenteditable][data-key]').forEach(el=>{const saved=localStorage.getItem('himked-'+el.dataset.key);if(saved)el.innerHTML=saved;el.addEventListener('input',()=>localStorage.setItem('himked-'+el.dataset.key,el.innerHTML));});}
function renderNav(active){nav.innerHTML=`<a class="${active==='beranda'?'active':''}" href="#beranda">Main Room <span>00</span></a>`+departments.map((d,i)=>`<a class="${active===d.id?'active':''}" href="#${d.id}">${d.name}<span>${String(i+1).padStart(2,'0')}</span></a>`).join('');}
function home(){app.innerHTML=document.querySelector('#home-template').innerHTML;renderNav('beranda');document.querySelector('#leaders').innerHTML=core.map(([name,role])=>`<article class="leader"><div class="avatar">${initials(name)}</div><div><p>${role}</p><h3 contenteditable="true" data-key="core-${name}">${name}</h3></div></article>`).join('');document.querySelector('#department-list').innerHTML=departments.map((d,i)=>`<a class="department-row" href="#${d.id}"><div class="dept-symbol">${d.icon}</div><h3>${d.name}</h3><p>${d.desc}</p><span class="arrow">↗</span></a>`).join(''); const agendas=[['Kelas Klinik','Akademik & Keilmuan',3],['Medical Charity','Sosial Masyarakat',11],['Pekan Olahraga Medika','Minat & Bakat',18]];document.querySelector('#agenda-list').innerHTML=agendas.map(([title,dept,plus])=>{let d=new Date();d.setDate(d.getDate()+plus);return `<article class="agenda-item"><time>${d.toLocaleDateString('id-ID',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase()}</time><div><h3>${title}</h3><p>${dept}</p></div><span>PROGRAM KERJA</span></article>`}).join('');saveEditable();}
function room(id){const d=departments.find(x=>x.id===id);if(!d)return home();app.innerHTML=document.querySelector('#department-template').innerHTML;renderNav(id);const index=departments.indexOf(d)+1;document.querySelector('#room-number').textContent=String(index).padStart(2,'0');document.querySelector('#room-icon').textContent=d.icon;document.querySelector('#room-eyebrow').textContent=`RUANG ${String(index).padStart(2,'0')} — DEPARTEMEN`;document.querySelector('#room-title').textContent=d.name;document.querySelector('#room-description').textContent=d.desc;const people=[[d.lead,d.role],['Nadia Putri','Sekretaris Departemen'],['Ardiansyah','Staf Program'],['Miftahul Jannah','Staf Program'],['Dimas Pratama','Staf Media'],['Salsabila','Staf Media']];document.querySelector('#team-list').innerHTML=people.map(([name,role])=>`<article class="team-member"><div class="mini-avatar">${initials(name)}</div><div><h3 contenteditable="true" data-key="${id}-${name}">${name}</h3><p>${role}</p></div></article>`).join('');const docs=['Rapat Kerja Departemen','Program Unggulan','Aksi Kolaborasi'];document.querySelector('#documentation').innerHTML=docs.map((x,i)=>`<article class="doc-card"><span>0${i+1} / ${new Date().getFullYear()}</span><h3>${x}</h3><p>${d.name}</p></article>`).join('');saveEditable();}
function route(){let id=location.hash.slice(1)||'beranda';const homeSections=['beranda','tentang','pengurus','departemen','program'];if(homeSections.includes(id)){home();requestAnimationFrame(()=>document.querySelector(id==='beranda'?'.hero':`#${id}`)?.scrollIntoView({block:'start'}));}else room(id);document.querySelector('#sidebar').classList.remove('open');}
window.addEventListener('hashchange',route);route();
const date=new Date();document.querySelector('#live-date').textContent=date.toLocaleDateString('id-ID',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).toUpperCase();document.querySelector('#year').textContent=date.getFullYear();
document.querySelector('.menu-toggle').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');
const panel=document.querySelector('#color-panel');document.querySelector('#customizer-toggle').onclick=()=>{panel.classList.toggle('open');document.querySelector('#customizer-toggle').setAttribute('aria-expanded',panel.classList.contains('open'));};
const defaults={forest:'#14532D',grass:'#4CAF50',yellow:'#FFC107'};document.querySelectorAll('[data-color]').forEach(input=>{let c=localStorage.getItem('color-'+input.dataset.color)||input.value;input.value=c;document.documentElement.style.setProperty('--'+input.dataset.color,c);input.oninput=()=>{document.documentElement.style.setProperty('--'+input.dataset.color,input.value);localStorage.setItem('color-'+input.dataset.color,input.value)}});document.querySelector('#reset-colors').onclick=()=>{Object.entries(defaults).forEach(([key,value])=>{localStorage.removeItem('color-'+key);document.documentElement.style.setProperty('--'+key,value);document.querySelector(`[data-color="${key}"]`).value=value})};
